version: "3.8"

services:
  acestream-proxy:
    build: .
    ports:
      - "16123:8000"
    env_file: .env
    networks:
      - acestream-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

networks:
  acestream-network:
    driver: bridge